ServDjango/urls.py
from django import urls
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('app.urls')),
    path('admin/', admin.site.urls),
]

app/urls.py
from django.urls import path
from .import views

app_name= 'app'

urlpatterns =[
    path('Home', views.index, name='index'), #Muestra Pag Principal
    path('Home_login_post', views.Home_login_post, name='Home_login_post'), # recoje los datos del login
    path('Home_registro_post', views.Home_registro_post, name='Home_registro_post'), # Recojer los datos del formulario
    path('Consul_List_Indi_Admin', views.Consul_Lista_Individuos_Admin, name='consu'),
    path('Pag_Admin', views.Pag_Admin, name='Pag_Admin'), # Pagina inicio de sesion Admin
    path('Pag_Usu', views.Pag_Usu, name='Pag_Usu'), # Pagina inicio de sesion Usuario
    path('', views.cerrar_sesion_post, name='cerrar_sesion_post'), # Boton cerrar sesion 
    path('Actualizar_Datos_Admin', views.Actualizar_Datos_Admin, name='Actualizar_Datos_Admin'), # Boton Actualizar Datos
    path('Actualizar_Datos_Post/<int:id_usuario>', views.Actualizar_Datos_Post, name='Actualizar_Datos_Post'), # Recoje Datos para actualizar
    path('Actualizar_Datos_Usu', views.Actualizar_Datos_Usu, name='Actualizar_Datos_Usu'), # Boton Actualizar Datos
    path('Crear_Partido_Politico', views.Crear_Partido_Politico, name='Crear_Partido_Politico'), # Boton Crear Partido Politico
    path('Crear_Partido_Politico_Post/<int:id_usuario>', views.Crear_Partido_Politico_Post, name='Crear_Partido_Politico_Post'), # Recoje Los Datos 
    path('Lista_Partido/<int:id_usuario>', views.Lista_Partido, name='Lista_Partido'), # Url Lista Partidos Admin
    path('Consular_PartidoP_Usuario',views.Consutar_PartidoP_Usuario,name='Consultar_Partido_Usuario'),#Url Consultar Partido
    path('Crear_Individuo_Admin',views.Crear_Individuo_Admin,name='Crear_Individuo_Admin'),#Boton Crear Individuo
    path('Crear_Individuo_Admin_Post/<int:id_usuario>', views.Crear_Individuo_Admin_Post, name='Crear_Individuo_Admin_Post'), # Recoje Los Datos 
    path('Crear_Individuo_Usu',views.Crear_Individuo_Usu,name='Crear_Individuo_Usu'),#Boton Crear Individuo
    path('Crear_Individuo_Usu_Post/<int:id_usuario>', views.Crear_Individuo_Usu_Post, name='Crear_Individuo_Usu_Post'), # Recoje Los Datos 
    #path('Lista_Individuo_Admin/<int:id_usuario>', views.Lista_Individuo_Admin, name='Lista_Individuo_Admin'), # Url Lista idivduos Admin
    path('Crear_Proceso_Admin',views.Crear_Proceso_Admin,name='Crear_Proceso_Admin'),#Boton Crear Proceso
    path('Crear_Proceso_Admin_Post', views.Crear_Proceso_Admin_Post, name='Crear_Proceso_Admin_Post'), # Recoje Los Datos
    path('Crear_Proceso_Usu',views.Crear_Proceso_Usu,name='Crear_Proceso_Usu'),#Boton Crear Proceso
    path('Crear_Proceso_Usu_Post/<int:id_usuario>', views.Crear_Proceso_Usu_Post, name='Crear_Proceso_Usu_Post'), # Recoje Los Datos
    path('Lista_Individuos/<int:id_usuario>', views.Lista_Individuos, name='Lista_Individuos'), # Url Lista idivduos Admin
]

app/templates/app/Actualizar_Datos_Admin.html
{% extends "app/Pag_Admin_Style.html" %}
{% load static %}
{% block extra_head %}
<link rel="stylesheet" href="{% static 'app/Actualizar_Datos.css' %}">
{% endblock %}

{% block title %}Actualizar Datos{% endblock %}

{% block main %}
<form action="{% url 'app:Actualizar_Datos_Post' request.user.id %}" method="POST">
    {% csrf_token %}
    <h1>Actualizar Datos</h1>
    <input type="text" placeholder="Nombres"  autocomplete="given-name" value="{{ request.user.first_name }}" name="nombres" > <br> <p></p>
    <input type="text" placeholder="Apellidos"  autocomplete="family-name" value="{{ request.user.last_name }}" name="apellidos"> <br> <p></p>
    <input type="text" placeholder="Usuario"  autocomplete="additional-name" value="{{ request.user.username }}" name="username"><br><p></p>
    <input type="password" placeholder="Nueva Contraseña" autocomplete="new-password" required name="password"> <br> <p></p>
    <input type="email" placeholder="Email" autocomplete="email" value="{{ request.user.email }}" name="email"> <br><p></p>
    <input class="form-boton" type="submit" value="Actualizar">  <br><p></p>  
    <br><p></p>            
</form>
{% endblock %}

app/templates/app/Consultar_PartidoP_Usuario.htm
{% extends "app/Pag_Usuario_Style.html" %}
{% load static %}
{% block title %} Consulta Partido {% endblock %}

{% block extra_head %}    
    <link rel="stylesheet" href="{% static 'app/Consul_PartidoP_Usu.css' %}">
{% endblock %}

{% block main %}
<form action="{% url 'app:Crear_Proceso_Admin_Post' %}" method="POST"></form>
{% csrf_token %}
<table class="table-proceso">            
    <thead>
        <td class="table_titulo" COLSPAN=2 >Procesos para partido: Partido Nombre </td>
        <tr>
            <th class="table-proceso-item">Total</th>
            <th class="table-proceso-item">Culpables</th>
        </tr>
</thead>



<table>
            
    <thead>
        
        <td class="table_titulo" COLSPAN=6 >Lista de afiliados</td>
        <tr>
            <th>Apellidos</th>
            <th>Nombres</th>
            <th>Fecha de ingreso</th>
            <th>Fecha de salida</th>
                             
        </tr>
    </thead>
    <tbody>
       {% for listas in lista %}
        <tr>
            <td><a href="Consultar_Individuo_Admin.html">{{ listas.Nombre }}</a></td>
            <td><a href="Consultar_Individuo_Admin.html">{{ listas.Apellidos }}</a></td>
            <td>a </td>

        </tr>
        {% endfor %}
    </tbody>
</table>
</form>
{% endblock %}

app/templates/app/Crear_Individuo_Usu.html
{% extends "app/Pag_Usuario_Style.html" %}
{% load static %}

{% block extra_head %}    
    <link rel="stylesheet" href="{% static 'app/Crear_individuo.css' %}">
{% endblock %}


{% block title %}Crear Individuo{% endblock %}

{% block main %}
<form action="{% url 'app:Crear_Individuo_Usu_Post' request.user.id %}" method="POST">
    {% csrf_token %}
    <h1>Crear Individuo</h1>
    <label for="">Apellidos</label>
    <input type="text" placeholder="Apellidos" name="Apellidos" id="Apellidos" required> <br> <p></p>
    <label for="">Nombre</label>
    <input type="text" placeholder="Nombres" name="Nombres" id="Nombre" required> <br> <p></p>
    <label for="">Fecha de Nacimiento</label>
    <input type="date" placeholder="Fecha de Nacimiento" name="Fecha de Nacimiento"  id="Fecha">
    <input class="form-boton" type="submit" value="Crear">  <br><p></p>  
    <br><p></p>            
</form>
{% endblock %}

app/templates/app/Crear_Partido_Politico_Exito.html
{% extends "app/Pag_Admin_Style.html" %}
{% load static %}
{% block extra_head %}

{% endblock %}

{% block title %}Actualizar Datos{% endblock %}

{% block main %}
<div style="margin-top: 350px">
    <h1 style="text-align:center">🟢 PARTIDO CREADO CON EXITO 🟢</h1>    
</div>

{% endblock %}

app/templates/app/Crear_Proceso_Admin.html
{% extends "app/Pag_Admin_Style.html" %}
{% load static %}


{% block extra_head %}    
    <link rel="stylesheet" href="{% static 'app/crear_proceso_admin.css' %}">
{% endblock %}

{% block title %}Crear Proceso{% endblock %}

{% block main %}
<form action="{% url 'app:Crear_Proceso_Admin_Post' %}" method="POST">
    {% csrf_token %}
    <h1>Crear Proceso</h1>
            <label for="">Título</label>
            <input type="text" placeholder="Título"  name="titulo" id="titulo"> <br> <br>
            <label for="" id="F_Inicio">Fecha de Inicio</label>
            <input type="date" name="F_Inicio"> <br> <br>
            <label for="" id="F_Fin">Fecha de Finalización</label>
            <input type="date" name="F_Fin"> <br> <br>
            <label for="">Abierto</label>
            <input type="checkbox" name="abierto" id="abierto"> <br> <br>
            <label for="">Entidad</label>
            <input type="text" placeholder="Entidad" name="entidad" id="entidad"> <br> <br>
            <label for="">Monto</label>
            <input type="text" placeholder="$" name="monto" id="monto"> <br> <br>
            <label for="" >Comentarios</label><br>
            <textarea name="comentarios" id="comentarios" placeholder="Escriba sus comentarios aquí" ></textarea><br>
            <input class="form-boton" type="submit" value="Crear"> <br>
                      
</form>
{% endblock %}

app/templates/app/Crear_Proceso_Exito.html
{% extends "app/Pag_Admin_Style.html" %}
{% load static %}
{% block extra_head %}

{% endblock %}

{% block title %}Actualizar Datos{% endblock %}

{% block main %}
<div style="margin-top: 350px">
    <h1 style="text-align:center">🟢 PROCESO CREADO CON EXITO 🟢</h1>    
</div>

{% endblock %}

app/templates/app/Crear_Proceso_Exito_Usu.html
{% extends "app/Pag_Usuario_Style.html" %}
{% load static %}
{% block extra_head %}

{% endblock %}

{% block title %}Actualizar Datos{% endblock %}

{% block main %}
<div style="margin-top: 350px">
    <h1 style="text-align:center">🟢 PROCESO CREADO CON EXITO 🟢</h1>    
</div>

{% endblock %}

app/templates/app/Error_Login.html
{% extends "app/index.html" %}

{% block info %}
<h1>ERROR INICIO DE SESSION</h1>
<h2 style="text-align:center">🚨 Por favor verficar credenciales 🚨</h2>
{% endblock %}

app/templates/app/Info_index.html
{% extends "app/index.html" %}

{% block info %}
<h1>CorPage</h1>
<p>Para mantener la transparencia  de los funcionarios públicos esta  plataforma en línea  esta diseñada para que los ciudadanos puedan consultar de una manera simple y rápida los hechos de corrupción gubernamental y los actores que intervinieron en el mismo.</p>
<p>Esta herramienta  web facilita el acceso a la información y la participación ciudadana, con el propósito de contribuir a combatir la corrupción en colombia. La plataforma permite que los usuarios entreguen sus denuncias, las cuales serán revisadas por un administrador. Si la denuncia es aceptada, el equipo redactará el reporte correspondiente a la denuncia y este será publicado en la plataforma.</p>
{% endblock %}

app/templates/app/Lista_Partidos_Usu.html
{% extends "app/Pag_Usuario_Style.html" %}
{% load static %}
{% block extra_head %}
<link rel="stylesheet" href="{% static 'app/Consul_Lista_Indivios.css' %}">
{% endblock %}

{% block title %}Lista partidos políticos{% endblock %}

{% block main %}
<table>
            
    <thead>
        
        <td class="table_titulo" COLSPAN=4 >Lista de partidos politicos</td>
        <tr>
            <th>Nombre partido</th>
            <th>Total visitas</th>
            <th>Total procesos</th> 
            <th>Consulta</th>                   
            </tr>
    </thead>
    <tbody>

        {% for L in listas %}
        <tr>
            <td><a href="#"> {{ L.nombre }}  </a></td>
            <td> {{L.visitas}} </td>
            <td>0</td> <!-- Toltal procesos -->
            <td><a href="#">🔎</a></td>
        </tr>
        {% endfor %}
        
    </tbody>
</table>

{% endblock %}

app/templates/app/Pag_Admin_Style.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Wellfleet&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'app/Pag_Admin_Style.css' %}">
    {% block extra_head %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
    


    
</head>
<body>    
    <header>
        <h1>CorPage</h1>
        <div class="botones">
            <a href="{% url 'app:Actualizar_Datos_Admin' %}" class="boton-cuenta">Cuenta</a>
            <a href="{% url 'app:cerrar_sesion_post' %}" class="boton-cerrar">Cerrar sesión</a>
        </div>        
    </header>
    <div class="barra-nav">

        <samp>ADMINISTRADOR</samp>
        <nav>
            <ul class="main-nav">                
                <li class="main-nav__item"><a href="">CONSULTAS ↧</a>
                    <ul>
                        <li class="main-nav__item-subm"><a href="{% url 'app:Lista_Individuos' request.user.id %}">✔ Lista individuos</a></li>                      
                        <li class="main-nav__item-subm"><a href="{% url 'app:Lista_Partido' request.user.id %}">✔ Lista partidos</a></li>                        
                    </ul>           
                 </li><br>

                <li class="main-nav__item"><a href="{% url 'app:Crear_Partido_Politico' %}">CREAR PARTIDO POLÍTICO</a></li>                
                <li class="main-nav__item"><a href="{% url 'app:Crear_Individuo_Admin' %}">CREAR INDIVIDUO</a></li>
                <li class="main-nav__item"><a href="{% url 'app:Crear_Proceso_Admin' %}">CREAR PROCESO</a></li>
                <li class="main-nav__item"><a href="Afiliar_a_partido.html">AFILIAR INDIVIDUO A PARTIDO</a></li>
                

                <li class="main-nav__item"><a href="Aprobar_Individuo.html">SOLICITUDES DE INDIVIDUOS</a></li>
                <li class="main-nav__item"><a href="Aprobar_Afiliacion.html">SOLICITUDES DE AFILIACIÓN DE INDIVIDUO</a></li>
                <li class="main-nav__item"><a href="Aprobar_Proceso.html">SOLICITUDES DE PROCESOS</a></li> <!-- APROBAR PROCESO -->                
                <li class="main-nav__item"><a href="Implicar_Afiliado_Admin.html">IMPLICAR AFILIADO A PROCESO</a></li>

                <li class="main-nav__item"><a href="Habiltar_Desabilitar_Ciudadano.html">CIUDADANOS</a></li>
                
            </ul>                        
        </nav>
        
    </div>

    <main>
        {% block main %}
        {% endblock %}
    </main>


</body>
</html>

app/templates/app/UsuActu_Error_Admin.html
{% extends "app/Pag_Admin_Style.html" %}
{% load static %}
{% block extra_head %}

{% endblock %}

{% block title %}Actualizar Datos{% endblock %}

{% block main %}
<div style="margin-top: 350px">
    <h1 style="text-align:center">ERROR, CUENTA SIN ACTUALIZAR </h1>
    <h2 style="text-align:center">🔴 Intente nuevamente con un usuario o correo diferente 🔴</h2>
</div>

{% endblock %}

app/templates/app/UsuActu_Exito_Usu.html
{% extends "app/Pag_Usuario_Style.html" %}
{% load static %}
{% block extra_head %}

{% endblock %}

{% block title %}Actualizar Datos{% endblock %}

{% block main %}
<div style="margin-top: 350px">
    <h1 style="text-align:center">CUENTA ACTUALIZADA CON EXITO</h1>
    <h2 style="text-align:center">🟢 Ahora puede volver a iniciar sesión 🟢</h2>
</div>

{% endblock %}

app/templates/app/index.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Para mantener la transparencia  de los funcionarios públicos esta  plataforma en línea  esta diseñada para que los ciudadanos puedan consultar de una manera simple y rápida los hechos de corrupción gubernamental y los actores que intervinieron en el mismo. ">
    <meta name="robots" content="index,follow">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Wellfleet&display=swap" rel="stylesheet">   
    <link rel="stylesheet" href="{% static 'app/PaginaPrin_Style.css' %}">
    <!-- <link rel="shortcut icon" href="#">  Para poner icono -->
    <title>Página inicial</title>
</head>
<body>
    <header>
        <h1>CorPage</h1>
        <form action="{% url 'app:Home_login_post' %}" method="POST">
            {% csrf_token %}
            <input type="text" placeholder="Usuario"  autocomplete="name" name="username">
            <input type="password" placeholder="Contraseña" autocomplete="current-password" name="password">            
            <input class="header-ingresar" type="submit" value="Ingresar">                
        </form>        
    </header>


    <div class="info-web">        
        <article>
            {% block info %}
            {% endblock %}            
        </article>

    </div>

    <main>

        <form action="{% url 'app:Home_registro_post' %}" method="POST" >
            {% csrf_token %}
            <h1>Registro</h1>
            <input type="text" placeholder="Nombres"  autocomplete="given-name" name="nombres" > <br> <p></p>
            <input type="text" placeholder="Apellidos"  autocomplete="family-name" name="apellidos" > <br> <p></p>
            <input type="text" placeholder="Usuario"  autocomplete="additional-name" name="username" required > <br> <p></p>
            <input type="password" placeholder="Contraseña" autocomplete="new-password" name="password" required> <br> <p></p>
            <input type="email" placeholder="Email" autocomplete="email" name="email" > <br><p></p>
            <input class="form-boton" type="submit" value="Registrarse">  <br><p></p>  
            <br><p></p>            
        </form>      

    </main>
    <footer>
        <div class="botones-footer">            
            <!-- <a href="Pag_Admin_Style.html" class="boton">Administrador</a>
            <a href="Pag_Usuario_Style.html" class="boton">Usuario</a>
            <a href="https://bitbucket.org/JonathannGuerrero/pagina_web" target="_blank" class="boton">BitBucket</a> -->
       </div> 
    </footer>    
</body>
</html>